/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.RegistroVentaController;
import controller.TipoCambioController;
import entity.RegistroVenta;
import entity.TipoCambio;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reportes.GenerarReporte;

/**
 *
 * @author ARCRODINPC-05
 */

public class CuentasXCobrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuentasPorCobrar
     */
    String filtro="c.razonSocial";
    int tabla;
    int idCliente;
    String razSocial;
    int idRegistroVenta;
    int idRegistroVentaTabla;
    static int idRegistroVentaStatic;
    String numero, serie;
    float cambioVenta;
    static String serieStaticCobro,numeroStaticCobro;
    
    public CuentasXCobrar() {
        initComponents();
        listaVentasCobrar(filtro, "%"+txtLike.getText()+"%");
        habilitarInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLike = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRazSocialReport = new javax.swing.JTextField();
        buttonReporteCobro = new javax.swing.JButton();
        buttonImprimirReporte = new javax.swing.JButton();
        buttonRegistroVenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRazSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtComprobante = new javax.swing.JTextField();
        txtNumComprobante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCambioVenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFormaPago = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMontoFactura = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDetraccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumCotizacion = new javax.swing.JTextField();
        buttonLimpiarInformacion = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cuentas por cobrar");

        txtLike.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLikeKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idRV", "idCli", "Comprobante", "F.Emisión", "Número Comp.", "Razón Social", "N° Ped.", "F. Vencimiento", "Tipo", "Moneda", "Monto Fact.", "Detracción", "Abonado", "Deuda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        }

        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "RAZÓN SOCIAL", "FACTURA" }));
        comboBoxFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxFiltroItemStateChanged(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idRVenta", "Factura", "F. Emisión", "Monto $", "Monto S/", "F. Vencimiento", "Deuda", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(110);
            jTable2.getColumnModel().getColumn(7).setPreferredWidth(220);
        }

        jLabel1.setText("Razón Social:");

        buttonReporteCobro.setText("PDF Reporte");
        buttonReporteCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReporteCobroActionPerformed(evt);
            }
        });

        buttonImprimirReporte.setText("Imprimir Reporte");
        buttonImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirReporteActionPerformed(evt);
            }
        });

        buttonRegistroVenta.setText("Ver Registro Venta");
        buttonRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistroVentaActionPerformed(evt);
            }
        });

        jLabel3.setText("Razón Social:");

        jLabel4.setText("Comprobante:");

        jLabel5.setText("Serie y Número:");

        jLabel6.setText("F. Emisión:");

        jLabel7.setText("F. Vencimiento:");

        jLabel8.setText("T.C. Venta:");

        jLabel9.setText("Tipo:");

        jLabel10.setText("Moneda:");

        jLabel11.setText("Forma  Pago:");

        jLabel12.setText("Monto Facturado:");

        jLabel13.setText("Detracción:");

        jLabel14.setText("Estado:");

        jLabel15.setText("Observación:");

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("N° Cot:");

        buttonLimpiarInformacion.setText("Limpiar");
        buttonLimpiarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarInformacionActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel16.setText("Todo comprobante para que no esté en la lista de cuentas por cobrar su estado debe ser \"CANCELADO\" o lo que usted considere. Para ver la lista de Estado, revisar la Vista de Ventas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazSocialReport, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLimpiarInformacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLike, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCambioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNumComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtRazSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14))))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buttonReporteCobro, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(buttonImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(buttonRegistroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMontoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRazSocialReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpiarInformacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonReporteCobro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImprimirReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRegistroVenta))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRazSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtMontoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtCambioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        limpiarTabla();
        tabla = jTable1.getSelectedRow();
        idCliente = Integer.parseInt(jTable1.getValueAt(tabla, 1).toString());
        razSocial = jTable1.getValueAt(tabla, 5).toString();
        txtRazSocialReport.setText(razSocial);
        listaVentasCobrarReporte("c.razonSocial", razSocial);
        habilitarBuscarReporte();
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboBoxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFiltroItemStateChanged
        if (comboBoxFiltro.getSelectedItem() == "RAZÓN SOCIAL") {
            filtro = "c.razonSocial";
            listaVentasCobrar(filtro, "%" + txtLike.getText() + "%");
            System.out.println(filtro);
        } else if (comboBoxFiltro.getSelectedItem() == "FACTURA") {
            filtro = "concat(rv.serie,'-', rv.numero)";
            listaVentasCobrar(filtro, "%" + txtLike.getText() + "%");
            System.out.println(filtro);
        } else if (comboBoxFiltro.getSelectedItem() == "SELECCIONAR") {
            filtro = "c.razonSocial";
            listaVentasCobrar(filtro, "%" + txtLike.getText() + "%");
            System.out.println(filtro);
        }
    }//GEN-LAST:event_comboBoxFiltroItemStateChanged

    private void txtLikeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLikeKeyReleased
        listaVentasCobrar(filtro,"%"+ txtLike.getText()+"%");
    }//GEN-LAST:event_txtLikeKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        limpiarInformacion();
        tabla = jTable2.getSelectedRow();
        idRegistroVentaTabla = Integer.parseInt(jTable2.getValueAt(tabla, 0).toString());
        try {
            consultarRegistroVenta(idRegistroVentaTabla);
        } catch (Exception ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarBuscarInformacion();
    }//GEN-LAST:event_jTable2MouseClicked

    private void buttonLimpiarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarInformacionActionPerformed
        limpiarInformacion();
        habilitarInicioInformacion();

    }//GEN-LAST:event_buttonLimpiarInformacionActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiarTabla();
        habilitarInicio();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            limpiarTabla();
            tabla = jTable1.getSelectedRow();
            idCliente = Integer.parseInt(jTable1.getValueAt(tabla, 1).toString());
            razSocial = jTable1.getValueAt(tabla, 5).toString();
            txtRazSocialReport.setText(razSocial);
            listaVentasCobrarReporte("c.razonSocial", razSocial);
            habilitarBuscarReporte();
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void buttonReporteCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReporteCobroActionPerformed
         GenerarReporte cuentasReport= new GenerarReporte();
        try {
            cuentasReport.ReporteCuentasCobrar(razSocial, "EN PROCESO");
        } catch (SQLException ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonReporteCobroActionPerformed

    private void buttonImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirReporteActionPerformed
        GenerarReporte cuentasReport= new GenerarReporte();
        try {
            cuentasReport.ImprimirCuentasCobrar(razSocial, "EN PROCESO");
        } catch (SQLException ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonImprimirReporteActionPerformed

    private void buttonRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistroVentaActionPerformed
        RegistroVentas reVet = null;
        try {
            reVet = new RegistroVentas();
        } catch (ParseException ex) {
            Logger.getLogger(CuentasXCobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal.jDesktopPane1.add(reVet);
        reVet.toFront();
        reVet.setVisible(true);
        RegistroVentas.serieYNumeroDeVentaDeCuentasPorCobrar();
    }//GEN-LAST:event_buttonRegistroVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonImprimirReporte;
    private javax.swing.JButton buttonLimpiarInformacion;
    private javax.swing.JButton buttonRegistroVenta;
    private javax.swing.JButton buttonReporteCobro;
    private javax.swing.JComboBox<String> comboBoxFiltro;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCambioVenta;
    private javax.swing.JTextField txtComprobante;
    private javax.swing.JTextField txtDetraccion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtFormaPago;
    private javax.swing.JTextField txtLike;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtMontoFactura;
    private javax.swing.JTextField txtNumComprobante;
    private javax.swing.JTextField txtNumCotizacion;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtRazSocial;
    private javax.swing.JTextField txtRazSocialReport;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
 
 RegistroVentaController registroventacontroler=new RegistroVentaController();
 RegistroVenta registroventa;
 
 TipoCambioController tipocambiocontroler = new TipoCambioController();
 TipoCambio tipocambio;
 
//--------------------------------------- Tabla 1 -----------------------------------------
    void listaVentasCobrar(String nombreFiltro, String valorFiltro) {
        List<RegistroVenta> lista;
        try {
            lista = registroventacontroler.RegistroVentaCuentasCobrar(nombreFiltro, valorFiltro);
            verVentas(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    void verVentas(List<RegistroVenta> lista) throws Exception {
        
        DefaultTableModel tabla1 = (DefaultTableModel) jTable1.getModel();
        tabla1.setRowCount(0);
        for (RegistroVenta reve : lista) {
            
            Object[] fila = {reve.getIdRegistroVenta(), reve.getIdCliente(),        reve.getTipoComprobante(),
                             reve.getFechaEmision(),    reve.getNumComprobante(),   reve.getRazonSocial(), 
                             reve.getNumPedido(),       reve.getFechaVencimiento(), reve.getTipo(), 
                             reve.getMoneda(),          reve.getMontoFacturado(),   reve.getDetraccion(), 
                             reve.getAbonado(),         reve.getDeuda()};
            tabla1.addRow(fila);
        }
    }
    
//--------------------------------------- Tabla 2 -----------------------------------------
    void listaVentasCobrarReporte(String nombreFiltro, String valorFiltro) {
        List<RegistroVenta> lista;
        try {
            lista = registroventacontroler.RegistroVentaCuentasCobrar(nombreFiltro, valorFiltro);
            verCobroReporte(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    void verCobroReporte(List<RegistroVenta> lista) throws Exception {
        String dol, sol;
        DefaultTableModel tabla1 = (DefaultTableModel) jTable2.getModel();
        tabla1.setRowCount(0);
        for (RegistroVenta reve : lista) {
            if ("SOLES".equals(reve.getMoneda())) {
                sol = reve.getMontoFacturado();
            } else {
                sol = "00.00";
            }
            if ("DOLARES AMERICANOS".equals(reve.getMoneda())) {
                dol = reve.getMontoFacturado();
            } else {
                dol = "00.00";
            }
                       
            Object[] fila = {reve.getIdRegistroVenta(),reve.getNumComprobante(),
                             reve.getFechaEmision(),dol,sol,reve.getFechaVencimiento(),
                             reve.getDeuda(), reve.getObservacion()};
            tabla1.addRow(fila);
        }
    }
    
//--------------------------- Consultar Registro Venta -------------------------
    
     private void consultarRegistroVenta(int id) throws Exception {
        registroventa = registroventacontroler.RegistroVentaPorId(id);
        if (registroventa != null) {
            
            
            idRegistroVenta=registroventa.getIdRegistroVenta();
            idRegistroVentaStatic=registroventa.getIdRegistroVenta();
            txtComprobante.setText(registroventa.getTipoComprobante());
            serie=registroventa.getSerie();
            serieStaticCobro=registroventa.getSerie();
            numero=registroventa.getNumero();
            numeroStaticCobro=registroventa.getNumero();
            txtNumComprobante.setText(serie+" - "+numero);
            txtRazSocial.setText(registroventa.getRazonSocial());
            txtNumCotizacion.setText(registroventa.getCodProforma());
            txtTipo.setText(registroventa.getTipo());
            txtFormaPago.setText(registroventa.getFormaPago());
            txtMoneda.setText(registroventa.getMoneda());
            txtFechaEmision.setText(registroventa.getFechaEmision());
            consultarTipoCambio(registroventa.getFechaEmision());
            txtFechaVencimiento.setText(registroventa.getFechaVencimiento());
            txtMontoFactura.setText(registroventa.getMontoFacturado());
            txtDetraccion.setText(registroventa.getDetraccion());
            txtEstado.setText(registroventa.getEstado());
            txtObservacion.setText(registroventa.getObservacion());
            
        } else {
            JOptionPane.showMessageDialog(null, "Pedido no registrado");
           
            System.out.println("Pedido no registrado");
        }
    }
     
     void consultarTipoCambio(String f) throws Exception {
        tipocambio =tipocambiocontroler.TipoCambioBuscarCambio(f) ;

        if (tipocambio != null) {
            cambioVenta=tipocambio.getPrecioVenta();
            txtCambioVenta.setText(Float.toString(tipocambio.getPrecioVenta()));
        } else {
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }
    }
    
//------------------------------------ Limpiar ---------------------------------
     
   void limpiarInformacion(){
   
       txtRazSocial.setText("");
       txtComprobante.setText("");
       txtNumComprobante.setText("");
       txtFechaEmision.setText("");
       txtCambioVenta.setText("");
       txtFechaVencimiento.setText("");
       txtTipo.setText("");
       txtMoneda.setText("");
       txtFormaPago.setText("");
       txtMontoFactura.setText("");
       txtDetraccion.setText("");
       txtEstado.setText("");
       txtObservacion.setText("");
       txtNumCotizacion.setText("");
   }
   
   void limpiarTabla(){
       txtRazSocial.setText("");
       txtComprobante.setText("");
       txtNumComprobante.setText("");
       txtFechaEmision.setText("");
       txtCambioVenta.setText("");
       txtFechaVencimiento.setText("");
       txtTipo.setText("");
       txtMoneda.setText("");
       txtFormaPago.setText("");
       txtMontoFactura.setText("");
       txtDetraccion.setText("");
       txtEstado.setText("");
       txtObservacion.setText("");
       txtNumCotizacion.setText("");
       txtRazSocialReport.setText("");
       listaVentasCobrarReporte(filtro,"");
   }
   
//------------------------- Habilitar ----------------------------------
   void habilitarInicio(){
       
       txtRazSocialReport.setEnabled(false);
       txtRazSocial.setEnabled(false);
       txtComprobante.setEnabled(false);
       txtNumComprobante.setEnabled(false);
       txtFechaEmision.setEnabled(false);
       txtCambioVenta.setEnabled(false);
       txtFechaVencimiento.setEnabled(false);
       txtTipo.setEnabled(false);
       txtMoneda.setEnabled(false);
       txtFormaPago.setEnabled(false);
       txtMontoFactura.setEnabled(false);
       txtDetraccion.setEnabled(false);
       txtEstado.setEnabled(false);
       txtObservacion.setEnabled(false);
       txtNumCotizacion.setEnabled(false);
       
       buttonReporteCobro.setEnabled(false);
       buttonImprimirReporte.setEnabled(false);
       buttonRegistroVenta.setEnabled(false);
       buttonLimpiarInformacion.setEnabled(false);
   }
   
   void habilitarBuscarReporte(){
   
       txtRazSocialReport.setEnabled(true);
       txtRazSocial.setEnabled(false);
       txtComprobante.setEnabled(false);
       txtNumComprobante.setEnabled(false);
       txtFechaEmision.setEnabled(false);
       txtCambioVenta.setEnabled(false);
       txtFechaVencimiento.setEnabled(false);
       txtTipo.setEnabled(false);
       txtMoneda.setEnabled(false);
       txtFormaPago.setEnabled(false);
       txtMontoFactura.setEnabled(false);
       txtDetraccion.setEnabled(false);
       txtEstado.setEnabled(false);
       txtObservacion.setEnabled(false);
       txtNumCotizacion.setEnabled(false);

       buttonReporteCobro.setEnabled(true);
       buttonImprimirReporte.setEnabled(true);
       buttonRegistroVenta.setEnabled(false);
       buttonLimpiarInformacion.setEnabled(false);
   }
   
   void habilitarBuscarInformacion(){
   
       txtRazSocialReport.setEnabled(false);
       txtRazSocial.setEnabled(true);
       txtComprobante.setEnabled(true);
       txtNumComprobante.setEnabled(true);
       txtFechaEmision.setEnabled(true);
       txtCambioVenta.setEnabled(true);
       txtFechaVencimiento.setEnabled(true);
       txtTipo.setEnabled(true);
       txtMoneda.setEnabled(true);
       txtFormaPago.setEnabled(true);
       txtMontoFactura.setEnabled(true);
       txtDetraccion.setEnabled(true);
       txtEstado.setEnabled(true);
       txtObservacion.setEnabled(true);
       txtNumCotizacion.setEnabled(true);

       buttonReporteCobro.setEnabled(true);
       buttonImprimirReporte.setEnabled(true);
       buttonRegistroVenta.setEnabled(true);
       buttonLimpiarInformacion.setEnabled(true);
   }

    void habilitarInicioTabla(){
       
       txtRazSocialReport.setEnabled(false);
       txtRazSocial.setEnabled(false);
       txtComprobante.setEnabled(false);
       txtNumComprobante.setEnabled(false);
       txtFechaEmision.setEnabled(false);
       txtCambioVenta.setEnabled(false);
       txtFechaVencimiento.setEnabled(false);
       txtTipo.setEnabled(false);
       txtMoneda.setEnabled(false);
       txtFormaPago.setEnabled(false);
       txtMontoFactura.setEnabled(false);
       txtDetraccion.setEnabled(false);
       txtEstado.setEnabled(false);
       txtObservacion.setEnabled(false);
       txtNumCotizacion.setEnabled(false);
       
       buttonReporteCobro.setEnabled(false);
       buttonImprimirReporte.setEnabled(false);
       buttonRegistroVenta.setEnabled(false);
       buttonLimpiarInformacion.setEnabled(false);
   }
   
    void habilitarInicioInformacion(){
       
       txtRazSocialReport.setEnabled(true);
       txtRazSocial.setEnabled(false);
       txtComprobante.setEnabled(false);
       txtNumComprobante.setEnabled(false);
       txtFechaEmision.setEnabled(false);
       txtCambioVenta.setEnabled(false);
       txtFechaVencimiento.setEnabled(false);
       txtTipo.setEnabled(false);
       txtMoneda.setEnabled(false);
       txtFormaPago.setEnabled(false);
       txtMontoFactura.setEnabled(false);
       txtDetraccion.setEnabled(false);
       txtEstado.setEnabled(false);
       txtObservacion.setEnabled(false);
       txtNumCotizacion.setEnabled(false);
       
       buttonReporteCobro.setEnabled(true);
       buttonImprimirReporte.setEnabled(true);
       buttonRegistroVenta.setEnabled(false);
       buttonLimpiarInformacion.setEnabled(false);
   }
   
}
