/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.RegistroPagoController;
import controller.RegistroVentaController;
import controller.TipoCambioController;
import entity.RegistroPago;
import entity.RegistroVenta;
import entity.TipoCambio;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.Destination;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.activemq.ActiveMQConnectionFactory;
import org.apache.log4j.BasicConfigurator;

/**
 *
 * @author ARCRODINPC-05
 */
public class RegistrarPago extends javax.swing.JInternalFrame {

    private static String url = "tcp://192.168.1.3:61616";
    private static String subject = "Cobranza";

    /**
     * Creates new form RegistrarPago
     */
    int idRegistroPago;
    static int idRegistroVentaPagoStatic;
    int idRegistroVenta;
    String tipoCombo;
    String monedaComboVenta;
    String detraccionCombo;
    boolean mensaje = true;
    float tipoCambioVenta;
    String fechaEmision;

    String monedaCombo;
    String tipoPagoCombo;

    float totalDolares;
    float totalSolesCalculo;
    float totalDetraccion;

    int tabla;

    DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();

    public RegistrarPago() throws Exception {

        initComponents();
        habilitarInicio();
        limpiarCuentas();
        jDateChooserFechaAbono.setCalendar(convertirFechaDate(fechaActual()));
//        idRegistroVenta = idRegistroVentaPagoStatic;
//        consultarRegistroVenta(idRegistroVenta);
//        listaRegistroPago(idRegistroVenta);
//        totalSoles(idRegistroVenta, fechaEmision);
//        totalDolares(idRegistroVenta, fechaEmision);
        labelRestoDolares.setOpaque(true);
        labelRestoDolares.setBackground(Color.YELLOW);
        labelRestoSoles.setOpaque(true);
        labelRestoSoles.setBackground(Color.YELLOW);
        jLabel16.setOpaque(true);
        jLabel16.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoComprobante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFormaPago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        txtTCVenta = new javax.swing.JTextField();
        txtFechaAprobacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        txtNumCotizacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ComboBoxTipoPago = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtMontoFacturado = new javax.swing.JTextField();
        labelSimboloSoles = new javax.swing.JLabel();
        txtMontoSoles = new javax.swing.JTextField();
        txtMontoDetraccion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jDateChooserFechaAbono = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBoxMonedaAbono = new javax.swing.JComboBox<>();
        txtMontoAbonado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroOperacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        buttonNuevo = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        comboBoxMoneda = new javax.swing.JComboBox<>();
        comboBoxDetraccion = new javax.swing.JComboBox<>();
        comboBoxTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        labelFacturaDolares = new javax.swing.JLabel();
        labelAbonadoDolares = new javax.swing.JLabel();
        labelRestoDolares = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelFacturaSoles = new javax.swing.JLabel();
        labelAbonadoSoles = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelRestoSoles = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonCerrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle(" Registrar Pago del Cliente");

        labelTipoComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoComprobante.setText("COMPROBANTE");

        jLabel2.setText("Serie:");

        jLabel3.setText("Número:");

        jLabel4.setText("Razón Social:");

        jLabel6.setText("Forma de Pago:");

        jLabel7.setText(" Moneda:");

        jLabel8.setText("Fecha Emisión:");

        jLabel10.setText("T.C.Venta:");

        jLabel12.setText("N° Pedido:");

        jLabel13.setText("N° Cotización:");

        jLabel18.setText("Tipo:");

        jLabel20.setText("Tipo de Pago:");

        ComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DETRACCION", "ABONO" }));
        ComboBoxTipoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxTipoPagoItemStateChanged(evt);
            }
        });

        jLabel21.setText("Fecha Aprobación:");

        jLabel22.setText("R.U.C.:");

        jLabel23.setText("Monto Facturado:");

        jLabel24.setText("Fecha Vencimiento:");

        jLabel25.setText("Detracción:");

        jLabel26.setText("Monto Detracción:");

        labelSimboloSoles.setText("S/.");

        jLabel28.setText("en Soles.");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel29.setText("Fecha de Abono:");

        jDateChooserFechaAbono.setDateFormatString("yyyy-MM-dd");

        jLabel5.setText("Moneda:");

        jLabel9.setText("Monto Abonado:");

        comboBoxMonedaAbono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOLARES AMERICANOS", "SOLES" }));
        comboBoxMonedaAbono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMonedaAbonoItemStateChanged(evt);
            }
        });

        jLabel11.setText("Número Operación:");

        jLabel14.setText("Observación:");

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        comboBoxMoneda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboBoxMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOLARES AMERICANOS", "SOLES" }));

        comboBoxDetraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "APLICA", "NO APLICA" }));

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PRODUCTO", "SERVICIO" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPago", "Tipo de Pago", "Fecha Abono", "Moneda", "MontoAbonado", "Número Operación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(280);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DOLARES AMERICANOS");

        labelFacturaDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFacturaDolares.setText("000000.00");

        labelAbonadoDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAbonadoDolares.setText("000000.00");

        labelRestoDolares.setBackground(new java.awt.Color(204, 204, 0));
        labelRestoDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRestoDolares.setText("000000.00");

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Monto Facturado:");

        jLabel42.setText("Monto Abonado:");

        jLabel43.setText("Resto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFacturaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAbonadoDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRestoDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE))))))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFacturaDolares)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAbonadoDolares)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRestoDolares)
                    .addComponent(jLabel43))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOLES");

        labelFacturaSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFacturaSoles.setText("000000.00");

        labelAbonadoSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAbonadoSoles.setText("000000.00");

        labelRestoSoles.setBackground(new java.awt.Color(255, 255, 51));
        labelRestoSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRestoSoles.setText("000000.00");

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Monto Facturado:");

        jLabel39.setText("Monto Abonado:");

        jLabel40.setText("Resto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel39)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel40)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFacturaSoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAbonadoSoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRestoSoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFacturaSoles)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAbonadoSoles)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRestoSoles)
                    .addComponent(jLabel40))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel16.setText("Obs: Tipo de cambio utilizado según la fecha de emisión del comprobante. Montos informativos y referenciales.");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Recibir de Facturación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel18)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazonSocial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTCVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMontoFacturado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMontoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(labelSimboloSoles)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMontoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28))))
                                    .addComponent(comboBoxDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDateChooserFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxMonedaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoComprobante)
                    .addComponent(jLabel2)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel24)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtMontoFacturado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSimboloSoles)
                    .addComponent(txtMontoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel10)
                    .addComponent(txtTCVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(comboBoxDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26)
                    .addComponent(txtMontoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxMonedaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumeroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserFechaAbono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonNuevo)
                            .addComponent(buttonRegistrar)
                            .addComponent(buttonModificar)
                            .addComponent(buttonGuardar)
                            .addComponent(buttonEliminar)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(buttonCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarNuevo();
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void comboBoxMonedaAbonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMonedaAbonoItemStateChanged
        if (comboBoxMonedaAbono.getSelectedIndex() != 0) {
            monedaCombo = comboBoxMonedaAbono.getSelectedItem().toString();
            System.out.println(monedaCombo);
        } else {
        }
    }//GEN-LAST:event_comboBoxMonedaAbonoItemStateChanged

    private void ComboBoxTipoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxTipoPagoItemStateChanged
        if (ComboBoxTipoPago.getSelectedIndex() != 0) {
            tipoPagoCombo = ComboBoxTipoPago.getSelectedItem().toString();
            System.out.println(tipoPagoCombo);
        } else {
            tipoPagoCombo = "";
        }
    }//GEN-LAST:event_ComboBoxTipoPagoItemStateChanged

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed

        if (ComboBoxTipoPago.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione opción según TIPO DE PAGO!!!");
        } else if (comboBoxMonedaAbono.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el TIPO DE MONEDA!!!");

        } else if ("".equals(txtMontoAbonado.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese alguna CANTIDAD!!!");

        } else {
            procesar(1);
            listaRegistroPago(idRegistroVenta);
            try {
                totalSoles(idRegistroVenta, fechaEmision);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalDolares(idRegistroVenta, fechaEmision);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                limpiar();
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            habilitarRegistrar();
        }

    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        procesar(2);
        listaRegistroPago(idRegistroVenta);
        try {
            totalSoles(idRegistroVenta, fechaEmision);
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            totalDolares(idRegistroVenta, fechaEmision);
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarGuardar();
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el registro, ¿desea continuar?",
                "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            procesar(3);
            listaRegistroPago(idRegistroVenta);
            try {
                totalSoles(idRegistroVenta, fechaEmision);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalDolares(idRegistroVenta, fechaEmision);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                limpiar();
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            habilitarEliminar();
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabla = jTable1.getSelectedRow();
        idRegistroPago = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());
        try {
            consultarRegistroPago(idRegistroPago);
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarBuscar();


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            try {
                limpiar();
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            tabla = jTable1.getSelectedRow();
            idRegistroPago = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());
            try {
                consultarRegistroPago(idRegistroPago);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
            habilitarBuscar();
        }

    }//GEN-LAST:event_jTable1KeyReleased

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        habilitarModificar();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarInicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCerrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        BasicConfigurator.configure();

        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(url);
        Connection connection = null;
        try {
            connection = connectionFactory.createConnection();
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            connection.start();
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        Session session = null;
        try {
            session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        Destination destination = null;
        try {
            destination = session.createQueue(subject);
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        MessageConsumer consumer = null;
        try {
            consumer = session.createConsumer(destination);
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        Message message = null;

        try {
            message = consumer.receive();
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (message instanceof TextMessage) {
            TextMessage textMessage = (TextMessage) message;
            try {

                String numero12 = null;
                numero12 = textMessage.getText(); // recibe el mensaje y lo carga

                idRegistroVenta = Integer.parseInt(numero12);

                try {
                    consultarRegistroVenta(idRegistroVenta);
                } catch (Exception ex) {
                    Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaRegistroPago(idRegistroVenta);
                try {
                    totalSoles(idRegistroVenta, fechaEmision);
                } catch (Exception ex) {
                    Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    totalDolares(idRegistroVenta, fechaEmision);
                } catch (Exception ex) {
                    Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (JMSException ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                //            JOptionPane.showMessageDialog(null, "Recepciona mensaje: '" + textMessage.getText() + "'");
                System.out.println("Recepciona mensaje: '" + textMessage.getText() + "'");
            } catch (JMSException ex) {
                Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            connection.close();
        } catch (JMSException ex) {
            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
        }

//        try {
//            consultarRegistroVenta(idRegistroVenta);
//        } catch (Exception ex) {
//            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        listaRegistroPago(idRegistroVenta);
//        try {
//            totalSoles(idRegistroVenta, fechaEmision);
//        } catch (Exception ex) {
//            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            totalDolares(idRegistroVenta, fechaEmision);
//        } catch (Exception ex) {
//            Logger.getLogger(RegistrarPago.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipoPago;
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> comboBoxDetraccion;
    private javax.swing.JComboBox<String> comboBoxMoneda;
    private javax.swing.JComboBox<String> comboBoxMonedaAbono;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooserFechaAbono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAbonadoDolares;
    private javax.swing.JLabel labelAbonadoSoles;
    private javax.swing.JLabel labelFacturaDolares;
    private javax.swing.JLabel labelFacturaSoles;
    private javax.swing.JLabel labelRestoDolares;
    private javax.swing.JLabel labelRestoSoles;
    private javax.swing.JLabel labelSimboloSoles;
    private javax.swing.JLabel labelTipoComprobante;
    private javax.swing.JTextField txtFechaAprobacion;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtFormaPago;
    private javax.swing.JTextField txtMontoAbonado;
    private javax.swing.JTextField txtMontoDetraccion;
    private javax.swing.JTextField txtMontoFacturado;
    private javax.swing.JTextField txtMontoSoles;
    private javax.swing.JTextField txtNumCotizacion;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroOperacion;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTCVenta;
    // End of variables declaration//GEN-END:variables

    RegistroVentaController registroventacontroler = new RegistroVentaController();
    RegistroVenta registroventa;

    RegistroPagoController registropagocontroler = new RegistroPagoController();
    RegistroPago registropago;

    TipoCambioController tipocambiocontroler = new TipoCambioController();
    TipoCambio tipocambio;

    //----------------------------- Procesar ------------------------------------
    void procesar(int op) {
        registropago = leerDatos();
        try {
            String msg = registropagocontroler.RegistroPagoProcesar(registropago, op);
            JOptionPane.showMessageDialog(null, msg);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Error" + e.getMessage());
        }
    }

    RegistroPago leerDatos() {
        RegistroPago repa = new RegistroPago();

        repa.setIdRegistroVenta(idRegistroVenta);
        repa.setTipoPago(tipoPagoCombo);
        repa.setFechaAbono(convertirFechaString(jDateChooserFechaAbono.getDate()));
        repa.setMoneda(monedaCombo);
        repa.setMontoAbonado(txtMontoAbonado.getText());
        repa.setNumeroOperacion(txtNumeroOperacion.getText());
        repa.setObservacion(txtObservacion.getText());
        repa.setIdRegistroPago(idRegistroPago);

        return repa;
    }

    //--------------------------- Consultar Registro Pago -----------------------
    private void consultarRegistroPago(int idrp) throws Exception {
        registropago = registropagocontroler.RegistroPagoBuscar(idrp);
        if (registropago != null) {

            idRegistroPago = registropago.getIdRegistroPago();
            idRegistroVenta = registropago.getIdRegistroVenta();
            tipoPagoCombo = registropago.getTipoPago();
            String testValuePago1 = tipoPagoCombo;
            for (int i = 0; i < ComboBoxTipoPago.getModel().getSize(); i++) {
                if (ComboBoxTipoPago.getItemAt(i).equals(testValuePago1)) {
                    System.out.println(i);
                    ComboBoxTipoPago.setSelectedIndex(i);
                    break;
                }
            }
            jDateChooserFechaAbono.setCalendar(convertirFechaDate(registropago.getFechaAbono()));
            monedaCombo = registropago.getMoneda();
            String testValuePago2 = monedaCombo;
            for (int i = 0; i < comboBoxMonedaAbono.getModel().getSize(); i++) {
                if (comboBoxMonedaAbono.getItemAt(i).equals(testValuePago2)) {
                    System.out.println(i);
                    comboBoxMonedaAbono.setSelectedIndex(i);
                    break;
                }
            }
            txtMontoAbonado.setText(registropago.getMontoAbonado());
            txtNumeroOperacion.setText(registropago.getNumeroOperacion());
            txtObservacion.setText(registropago.getObservacion());

        } else {
            JOptionPane.showMessageDialog(null, "Pedido no registrado");

            System.out.println("Pedido no registrado");
        }
    }

    //-------------------------------Buscar RegistroVenta -----------------------
    private void consultarRegistroVenta(int id) throws Exception {
        registroventa = registroventacontroler.RegistroVentaPorId(id);
        if (registroventa != null) {

            idRegistroVenta = registroventa.getIdRegistroVenta();
            labelTipoComprobante.setText(registroventa.getTipoComprobante());
            txtSerie.setText(registroventa.getSerie());
            txtNumero.setText(registroventa.getNumero());
            txtRazonSocial.setText(registroventa.getRazonSocial());
            txtRuc.setText(registroventa.getRuc());
            txtNumPedido.setText(String.format("%06d", Integer.parseInt(registroventa.getNumPedido())));
            txtNumCotizacion.setText(registroventa.getCodProforma());

            tipoCombo = registroventa.getTipo();
            String testValue1 = tipoCombo;
            for (int i = 0; i < comboBoxTipo.getModel().getSize(); i++) {
                if (comboBoxTipo.getItemAt(i).equals(testValue1)) {
                    System.out.println(i);
                    comboBoxTipo.setSelectedIndex(i);
                    break;
                }
            }

            txtFormaPago.setText(registroventa.getFormaPago());

            monedaComboVenta = registroventa.getMoneda();
            String testValue2 = monedaComboVenta;
            for (int i = 0; i < comboBoxMoneda.getModel().getSize(); i++) {
                if (comboBoxMoneda.getItemAt(i).equals(testValue2)) {
                    System.out.println(i);
                    comboBoxMoneda.setSelectedIndex(i);
                    break;
                }
            }

            txtFechaEmision.setText(registroventa.getFechaEmision());
            fechaEmision = registroventa.getFechaEmision();
            consultarTipoCambio(registroventa.getFechaEmision());
            txtFechaAprobacion.setText(registroventa.getFechaAprobacion());
            txtFechaVencimiento.setText(registroventa.getFechaVencimiento());
            txtMontoFacturado.setText(registroventa.getMontoFacturado());

            detraccionCombo = registroventa.getDetraccion();
            String testValue3 = detraccionCombo;
            for (int i = 0; i < comboBoxDetraccion.getModel().getSize(); i++) {
                if (comboBoxDetraccion.getItemAt(i).equals(testValue3)) {
                    System.out.println(i);
                    comboBoxDetraccion.setSelectedIndex(i);
                    break;
                }
            }
            calcularMontoDetraccionYMontoSoles();

        } else {
            JOptionPane.showMessageDialog(null, "Pedido no registrado");

            System.out.println("Pedido no registrado");
        }
    }

//-------------------------- Busqueda Tipo Cambio ---------------------------
    void consultarTipoCambio(String f) throws Exception {
        tipocambio = tipocambiocontroler.TipoCambioBuscarCambio(f);

        if (tipocambio != null) {
            mensaje = true;
            tipoCambioVenta = tipocambio.getPrecioVenta();
            txtTCVenta.setText(Float.toString(tipocambio.getPrecioVenta()));
        } else {
            mensaje = false;
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }
    }

    //---------------- Total Soles y Dolares de los Pagos ------------------------------
    void totalSoles(int idrv, String f) throws Exception {
        registropago = registropagocontroler.RegistroPagoTotalSoles(idrv, f);

        if (registropago != null) {
            labelFacturaSoles.setText(registropago.getMontoFactura());
            labelAbonadoSoles.setText(registropago.getMontoAbonado());
            labelRestoSoles.setText(registropago.getResto());
        } else {

//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }

    }

    void totalDolares(int idrvd, String fd) throws Exception {
        registropago = registropagocontroler.RegistroPagoTotalDolares(idrvd, fd);

        if (registropago != null) {
            labelFacturaDolares.setText(registropago.getMontoFactura());
            labelAbonadoDolares.setText(registropago.getMontoAbonado());
            labelRestoDolares.setText(registropago.getResto());
        } else {
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }

    }

// ------------------------------------ TABLA ---------------------------------------
    void listaRegistroPago(int idreve) {
        List<RegistroPago> lista;
        try {
            lista = registropagocontroler.RegistroPagoListar(idreve);
            verListaPagos(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verListaPagos(List<RegistroPago> lista) {

        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        tabla.setRowCount(0);
        for (RegistroPago repago : lista) {

            Object[] fila = {repago.getIdRegistroPago(), repago.getTipoPago(), repago.getFechaAbono(),
                repago.getMoneda(), repago.getMontoAbonado(), repago.getNumeroOperacion()};
            tabla.addRow(fila);
        }
    }

//-------------------------------- Manejo de Fechas ---------------------------
    public String fechaActual() {
        Date fecha = new Date();

        SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatofecha.format(fecha);
    }

    Calendar convertirFechaDate(String ah) throws ParseException {

        Calendar fecha = Calendar.getInstance();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaDate = null;

        fechaDate = formato.parse(ah);

        fecha.setTime(fechaDate);

        return fecha;
    }

    String convertirFechaString(Date fech) {

        Format formatter = new SimpleDateFormat("yyyy-MM-dd ");

        return formatter.format(fech);

    }

//    ----------------------- Muestra el monto en soles si en caso fuese dolares 
//                            y calcula el valor de detraccion segun el monto facturado  --------------------------
    void calcularMontoDetraccionYMontoSoles() {
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat df = new DecimalFormat("0.000", separadoresPersonalizados);

        try {
            consultarTipoCambio(txtFechaEmision.getText());
        } catch (Exception ex) {
            Logger.getLogger(RegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (comboBoxMoneda.getSelectedIndex() == 1) {

            try {
                consultarTipoCambio(txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtMontoSoles.setEnabled(true);
            labelSimboloSoles.setText("S/.");
            totalDolares = Float.parseFloat(txtMontoFacturado.getText());
            totalSolesCalculo = totalDolares * tipoCambioVenta;
            txtMontoSoles.setText(df.format(totalSolesCalculo));

            if (comboBoxTipo.getSelectedIndex() == 2) {

                if (comboBoxDetraccion.getSelectedIndex() == 1) {

                    totalDetraccion = (float) (Float.parseFloat(txtMontoSoles.getText()) * 0.12);
                    txtMontoDetraccion.setText(df.format(totalDetraccion));

                } else if (comboBoxDetraccion.getSelectedIndex() == 2) {

                    txtMontoDetraccion.setText("");

                }

            } else if (comboBoxTipo.getSelectedIndex() == 1) {
                txtMontoDetraccion.setText("");
            }

        } else if (comboBoxMoneda.getSelectedIndex() == 2) {

            txtMontoSoles.setEnabled(false);
            txtMontoSoles.setText("");
            labelSimboloSoles.setText("");
            totalSolesCalculo = Float.parseFloat(txtMontoFacturado.getText());

            if (comboBoxTipo.getSelectedIndex() == 2) {

                if (comboBoxDetraccion.getSelectedIndex() == 1) {

                    totalDetraccion = (float) (totalSolesCalculo * 0.12);
                    txtMontoDetraccion.setText(df.format(totalDetraccion));

                } else if (comboBoxDetraccion.getSelectedIndex() == 2) {

                    txtMontoDetraccion.setText("");

                }
            } else if (comboBoxTipo.getSelectedIndex() == 1) {
                txtMontoDetraccion.setText("");
            }
        }

    }

//------------------------------- Limpiar --------------------------------------
    void limpiar() throws ParseException {
        ComboBoxTipoPago.setSelectedIndex(0);
        jDateChooserFechaAbono.setCalendar(convertirFechaDate(fechaActual()));
        comboBoxMonedaAbono.setSelectedIndex(0);
        txtMontoAbonado.setText("");
        txtNumeroOperacion.setText("");
        txtObservacion.setText("");
    }

    void limpiarCuentas() {
        labelFacturaSoles.setText("000000.00");
        labelAbonadoSoles.setText("000000.00");
        labelRestoSoles.setText("000000.00");

        labelFacturaDolares.setText("000000.00");
        labelAbonadoDolares.setText("000000.00");
        labelRestoDolares.setText("000000.00");

    }

//--------------------------------- Habilitar ----------------------------------
    void habilitarInicio() {

        ComboBoxTipoPago.setEnabled(false);
        jDateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaAbono.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }

    void habilitarNuevo() {

        ComboBoxTipoPago.setEnabled(true);
        jDateChooserFechaAbono.setEnabled(true);
        comboBoxMonedaAbono.setEnabled(true);
        txtMontoAbonado.setEnabled(true);
        txtNumeroOperacion.setEnabled(true);
        txtObservacion.setEnabled(true);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(true);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);

    }

    void habilitarRegistrar() {

        ComboBoxTipoPago.setEnabled(false);
        jDateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaAbono.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }

    void habilitarBuscar() {

        ComboBoxTipoPago.setEnabled(false);
        jDateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaAbono.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(true);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(true);
    }

    void habilitarModificar() {

        ComboBoxTipoPago.setEnabled(true);
        jDateChooserFechaAbono.setEnabled(true);
        comboBoxMonedaAbono.setEnabled(true);
        txtMontoAbonado.setEnabled(true);
        txtNumeroOperacion.setEnabled(true);
        txtObservacion.setEnabled(true);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(true);
        buttonEliminar.setEnabled(false);
    }

    void habilitarGuardar() {

        ComboBoxTipoPago.setEnabled(false);
        jDateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaAbono.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }

    void habilitarEliminar() {

        ComboBoxTipoPago.setEditable(false);
        jDateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaAbono.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }
}
