/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.ComprobanteSunatController;
import controller.GlosaController;
import controller.ProveedorController;
import controller.RegistroCompraController;
import controller.RegistroPagoCompraController;
import controller.TipoCambioController;
import entity.ComprobanteSunat;
import entity.Glosa;
import entity.Proveedor;
import entity.RegistroCompra;
import entity.RegistroPagoCompra;
import entity.TipoCambio;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCRODINPC-05
 */
public class RegistrarPagosCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarPagosCompra
     */
    int idRegistroPagoCompra;
    int idRegistroCompra;
    static int idRegistroCompraStatic;
    int idProveedor;
    int idComprobante;
    int idGlosa;
    String tipoCambioVenta;
    String monedaCombo;
    String detraccionCombo;
    String tipoPagoCombo;
    String monedaPagoCombo;
    float totalDolares;
    float totalSolesCalculo;
    float totalDetraccion;
    int tabla;
    
    DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
    
    public RegistrarPagosCompra() throws Exception, Exception {
        initComponents();
        habilitarInicio();
        idRegistroCompra=idRegistroCompraStatic;               
        consultarRegistroCompra(idRegistroCompra);
        listaRegistroPagoCompra(idRegistroCompra);
        dateChooserFechaAbono.setCalendar(convertirFechaDate(fechaActual()));
        labelRestoDolares.setOpaque(true);
        labelRestoDolares.setBackground(Color.YELLOW);
        labelRestoSoles.setOpaque(true);
        labelRestoSoles.setBackground(Color.YELLOW);
        labelObs.setOpaque(true);
        labelObs.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelComprobante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOrdenCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoCambio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaAprobacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboBoxMoneda = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        labelSimbolo = new javax.swing.JLabel();
        txtMontoSoles = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboBoxDetraccion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtMontoDetraccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        comboBoxTipoPago = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        dateChooserFechaAbono = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        comboBoxMonedaPago = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtMontoAbonado = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNumeroOperacion = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        buttonNuevo = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        labelMontoSoles = new javax.swing.JLabel();
        labelAbonadoSoles = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        labelRestoSoles = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        labelMo = new javax.swing.JLabel();
        labelAbo = new javax.swing.JLabel();
        labelMontoDolares = new javax.swing.JLabel();
        labelAbonadoDolares = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        labelRestoDolares = new javax.swing.JLabel();
        labelObs = new javax.swing.JLabel();
        buttonLimpiar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonCerrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar Pagos de Compra");

        labelComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComprobante.setText("COMPROBANTE");

        jLabel2.setText("Serie:");

        jLabel3.setText("Número:");

        jLabel4.setText("Razón Social:");

        jLabel5.setText("R.U.C:");

        jLabel6.setText("N° O.Compra:");

        jLabel7.setText("Fecha Emisión:");

        jLabel8.setText("T.C.:");

        jLabel9.setText("Fecha Aprobación:");

        jLabel10.setText("Fecha Vencimiento:");

        jLabel11.setText("Moneda:");

        comboBoxMoneda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboBoxMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOLARES AMERICANOS", "SOLES" }));

        jLabel12.setText("Concepto:");

        jLabel13.setText("Monto:");

        labelSimbolo.setText("S/");

        jLabel15.setText("Detracción:");

        comboBoxDetraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "APLICA", "NO APLICA" }));

        jLabel16.setText("Monto Detracción:");

        jLabel17.setText("en Soles");

        jLabel18.setText("Tipo de Pago:");

        comboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DETRACCION", "ABONO" }));
        comboBoxTipoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTipoPagoItemStateChanged(evt);
            }
        });

        jLabel19.setText("Fecha de Abono:");

        dateChooserFechaAbono.setDateFormatString("yyyy-MM-dd");

        jLabel20.setText("Moneda:");

        comboBoxMonedaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOLARES AMERICANOS", "SOLES" }));
        comboBoxMonedaPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxMonedaPagoItemStateChanged(evt);
            }
        });

        jLabel21.setText("Monto Abonado:");

        jLabel22.setText("N° Operación:");

        jLabel23.setText("Observación:");

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPagoCompra", "Tipo de Pago ", "Fecha Abono", "Moneda", "Monto Abonado", "N° Operación", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(105);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(275);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("SOLES");

        jLabel26.setText("Monto Total:");

        jLabel27.setText("Monto Abonado:");

        labelMontoSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMontoSoles.setText("000000.00");

        labelAbonadoSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAbonadoSoles.setText("000000.00");

        jLabel34.setText("Resto:");

        labelRestoSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRestoSoles.setText("000000.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelMontoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAbonadoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelRestoSoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(labelMontoSoles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(labelAbonadoSoles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(labelRestoSoles))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("DOLARES AMERICANOS");

        labelMo.setText("Monto Total:");

        labelAbo.setText("Monto Abonado:");

        labelMontoDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMontoDolares.setText("000000.00");

        labelAbonadoDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAbonadoDolares.setText("000000.00");

        jLabel35.setText("Resto:");

        labelRestoDolares.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRestoDolares.setText("000000.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMo)
                                    .addComponent(labelAbo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMontoDolares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAbonadoDolares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRestoDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMo)
                    .addComponent(labelMontoDolares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAbo)
                    .addComponent(labelAbonadoDolares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(labelRestoDolares))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        labelObs.setText("Obs: Tipo de cambio utilizado según la fecha de emisión del comprobante. Montos informativos y referenciales.");

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(comboBoxTipoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(dateChooserFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(comboBoxMonedaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel22))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel23)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNumeroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelObs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(labelComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMontoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comboBoxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel15)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMontoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17))))
                                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComprobante)
                    .addComponent(jLabel2)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(comboBoxDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(comboBoxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtMontoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSimbolo)
                    .addComponent(txtMontoSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(comboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(comboBoxMonedaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtNumeroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(dateChooserFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuevo)
                    .addComponent(buttonRegistrar)
                    .addComponent(buttonModificar)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonLimpiar)
                    .addComponent(buttonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObs)
                    .addComponent(buttonCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        if (comboBoxTipoPago.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar el Tipo de Pago, REVISAR!!!");
        } else if (comboBoxMonedaPago.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar Moneda, REVISAR!!!");
        } else if ("".equals(txtMontoAbonado.getText())) {
            JOptionPane.showMessageDialog(null, "Indicar el Monto Abonado, REVISAR!!!");
        } else{

            procesar(1);
            listaRegistroPagoCompra(idRegistroCompra);
            try {
                totalSoles(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalDolares(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            habilitarRegistrar();
            try {
                limpiar();
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Se MODIFICARÁ el registro, ¿desea continuar?",
                "Modificar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            procesar(2);
            try {
                consultarRegistroPagoCompra(idRegistroPagoCompra);
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalSoles(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalDolares(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            listaRegistroPagoCompra(idRegistroCompra);
            habilitarGuardar();
        }else{
            habilitarBuscar();
        }
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el registro, ¿desea continuar?",
                "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            procesar(3);
            try {
                totalSoles(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                totalDolares(idRegistroCompra, txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            listaRegistroPagoCompra(idRegistroCompra);
            habilitarEliminar();
            try {
                limpiar();
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            habilitarBuscar();
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabla = jTable1.getSelectedRow();
        idRegistroPagoCompra = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());
        try {
            consultarRegistroPagoCompra(idRegistroPagoCompra);
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarBuscar();
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        habilitarInicio();
        try {
            limpiar();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPagosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void comboBoxMonedaPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxMonedaPagoItemStateChanged
        if (comboBoxMonedaPago.getSelectedIndex() != 0) {
            monedaPagoCombo = comboBoxMonedaPago.getSelectedItem().toString();
            System.out.println(monedaPagoCombo);
        } else {
        }
    }//GEN-LAST:event_comboBoxMonedaPagoItemStateChanged

    private void comboBoxTipoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTipoPagoItemStateChanged
        if (comboBoxTipoPago.getSelectedIndex() != 0) {
            tipoPagoCombo = comboBoxTipoPago.getSelectedItem().toString();
            System.out.println(tipoPagoCombo);
        } else {
        }
    }//GEN-LAST:event_comboBoxTipoPagoItemStateChanged

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        habilitarNuevo();
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        habilitarModificar();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> comboBoxDetraccion;
    private javax.swing.JComboBox<String> comboBoxMoneda;
    private javax.swing.JComboBox<String> comboBoxMonedaPago;
    private javax.swing.JComboBox<String> comboBoxTipoPago;
    private com.toedter.calendar.JDateChooser dateChooserFechaAbono;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAbo;
    private javax.swing.JLabel labelAbonadoDolares;
    private javax.swing.JLabel labelAbonadoSoles;
    private javax.swing.JLabel labelComprobante;
    private javax.swing.JLabel labelMo;
    private javax.swing.JLabel labelMontoDolares;
    private javax.swing.JLabel labelMontoSoles;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelRestoDolares;
    private javax.swing.JLabel labelRestoSoles;
    private javax.swing.JLabel labelSimbolo;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtFechaAprobacion;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtMontoAbonado;
    private javax.swing.JTextField txtMontoDetraccion;
    private javax.swing.JTextField txtMontoSoles;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroOperacion;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtOrdenCompra;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTipoCambio;
    // End of variables declaration//GEN-END:variables
    
    RegistroCompraController registrocompracontroler=new  RegistroCompraController();
    RegistroCompra registrocompra;
    
    RegistroPagoCompraController registropagocompracontroler= new RegistroPagoCompraController();
    RegistroPagoCompra registropagocompra;
    
    ProveedorController proveedorcontroler=new ProveedorController();
    Proveedor proveedor;
    
    ComprobanteSunatController comprobantecontroler=new ComprobanteSunatController();
    ComprobanteSunat comprobante;
    
    TipoCambioController tipocambiocontroler= new TipoCambioController();
    TipoCambio tipocambio;
    
    GlosaController glosacontroler= new GlosaController();
    Glosa glosa;
    
    
// -------------------------------- Buscar Registro Compra --------------------------------------
    private void consultarRegistroCompra(int idRepaco) throws Exception {
        registrocompra = registrocompracontroler.RegistroCompraBuscar(idRepaco);
        if (registrocompra != null) {

            idRegistroCompra = registrocompra.getIdRegistroCompra();
            totalSoles(registrocompra.getIdRegistroCompra(), registrocompra.getFechaEmision());
            totalDolares(registrocompra.getIdRegistroCompra(), registrocompra.getFechaEmision());
            idProveedor = registrocompra.getIdProveedor_fk();
            consultarProveedor(registrocompra.getIdProveedor_fk());
            txtOrdenCompra.setText(registrocompra.getNumOrdenCompra());
            idComprobante = registrocompra.getIdComprobanteSunat_fk();
            consultarComprobante(registrocompra.getIdComprobanteSunat_fk());
            txtSerie.setText(registrocompra.getSerie());
            txtNumero.setText(registrocompra.getNumero());
            txtFechaEmision.setText(registrocompra.getFechaEmision());
            consultarTipoCambio(registrocompra.getFechaEmision());
            txtFechaAprobacion.setText(registrocompra.getFechaAprobacion());
            txtFechaVencimiento.setText(registrocompra.getFechaVencimiento());
            idGlosa = registrocompra.getIdGlosa_fk();
            consultarGlosa(idGlosa);
            monedaCombo = registrocompra.getMoneda();
            String testValue1 = monedaCombo;
            for (int i = 0; i < comboBoxMoneda.getModel().getSize(); i++) {
                if (comboBoxMoneda.getItemAt(i).equals(testValue1)) {
                    System.out.println(i);
                    comboBoxMoneda.setSelectedIndex(i);
                    break;
                }
            }

            txtMontoTotal.setText(registrocompra.getMontoFacturado());

            detraccionCombo = registrocompra.getDetraccion();
            String testValue2 = detraccionCombo;
            for (int i = 0; i < comboBoxDetraccion.getModel().getSize(); i++) {
                if (comboBoxDetraccion.getItemAt(i).equals(testValue2)) {
                    System.out.println(i);
                    comboBoxDetraccion.setSelectedIndex(i);
                    break;
                }
            }

            calcularMontoDetraccionYMontoSoles();

        } else {
            JOptionPane.showMessageDialog(null, "Venta no registrado");
            System.out.println("Venta no registrada");
        }
    }

    private void consultarProveedor(int idProvee) throws Exception {
        proveedor = proveedorcontroler.ProveedorBuscarId(idProvee);
        if (proveedor != null) {

            idProveedor = proveedor.getIdProveedor();
            // txtNombres.setText(pro.getNombres());
            txtRazonSocial.setText(proveedor.getRazonSocial());
            txtRuc.setText(proveedor.getRuc());

        } else {
            JOptionPane.showMessageDialog(null, "Proveedor no registrado");
            //System.out.println("Error");
        }
    }

    private void consultarComprobante(int idComprob) throws Exception {
        comprobante = comprobantecontroler.ComprobanteSunatBuscar(idComprob);
        if (comprobante != null) {

            idComprobante = comprobante.getIdComprobanteSunat();
            labelComprobante.setText(comprobante.getDescripcion());

        } else {
            JOptionPane.showMessageDialog(null, "Comprobante no registrado");
            //System.out.println("Error");
        }
    }

    void consultarTipoCambio(String f) throws Exception {
        tipocambio = tipocambiocontroler.TipoCambioBuscarCambio(f);

        if (tipocambio != null) {

            tipoCambioVenta = Float.toString(tipocambio.getPrecioVenta());
            txtTipoCambio.setText(Float.toString(tipocambio.getPrecioVenta()));

        } else {
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }
    }

    private void consultarGlosa(int idGlosa) throws Exception {
        glosa = glosacontroler.GlosaBuscar(idGlosa);
        if (glosa != null) {

            idGlosa = glosa.getIdGlosa();
            txtConcepto.setText(glosa.getConcepto());

        } else {
            JOptionPane.showMessageDialog(null, "Glosa no registrada");
            //System.out.println("Error");
        }
    }

    //    ----------------------- Muestra el monto en soles si en caso fuese dolares 
//                            y calcula el valor de detraccion segun el monto facturado  --------------------------
    void calcularMontoDetraccionYMontoSoles() throws Exception {
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat df = new DecimalFormat("0.000", separadoresPersonalizados);

        consultarTipoCambio(txtFechaEmision.getText());

        if (comboBoxMoneda.getSelectedIndex() == 1) {

            try {
                consultarTipoCambio(txtFechaEmision.getText());
            } catch (Exception ex) {
                Logger.getLogger(RegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtMontoSoles.setEnabled(true);
            labelSimbolo.setText("S/.");
            totalDolares = Float.parseFloat(txtMontoTotal.getText());
            totalSolesCalculo = totalDolares * Float.parseFloat(tipoCambioVenta);
            txtMontoSoles.setText(df.format(totalSolesCalculo));

            if (comboBoxDetraccion.getSelectedIndex() == 1) {

                totalDetraccion = (float) (Float.parseFloat(txtMontoSoles.getText()) * 0.12);
                txtMontoDetraccion.setText(df.format(totalDetraccion));

            } else if (comboBoxDetraccion.getSelectedIndex() == 2) {

                txtMontoDetraccion.setText("");

            }

        } else if (comboBoxMoneda.getSelectedIndex() == 2) {

            txtMontoSoles.setEnabled(false);
            txtMontoSoles.setText("");
            labelSimbolo.setText("");
            totalSolesCalculo = Float.parseFloat(txtMontoTotal.getText());

            if (comboBoxDetraccion.getSelectedIndex() == 1) {

                totalDetraccion = (float) (totalSolesCalculo * 0.12);
                txtMontoDetraccion.setText(df.format(totalDetraccion));

            } else if (comboBoxDetraccion.getSelectedIndex() == 2) {

                txtMontoDetraccion.setText("");
            }
        }
    }

// ------------------------------- Procesar ------------------------------------
  
    
    void procesar(int op) {
        registropagocompra = leerDatos();
        try {
                 String msg = registropagocompracontroler.RegistroPagoCompraProcesar(registropagocompra, op);
            JOptionPane.showMessageDialog(null, msg);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Error" + e.getMessage());
        }
    } 

    
    RegistroPagoCompra leerDatos() {
        RegistroPagoCompra repaco = new RegistroPagoCompra();
        
        repaco.setIdRegistroComprafk(idRegistroCompra);
        repaco.setTipoPago(tipoPagoCombo);
        repaco.setFechaAbono(convertirFechaString(dateChooserFechaAbono.getDate()));
        repaco.setMoneda(monedaPagoCombo);
        repaco.setMontoAbonado(txtMontoAbonado.getText());
        repaco.setNumeroOperacion(txtNumeroOperacion.getText());
        repaco.setObservacion(txtObservacion.getText());
        repaco.setIdRegistroPagoCompra(idRegistroPagoCompra);

        return repaco;
    }
    
//---------------------------- Registro Pago Compra ---------------------
    private void consultarRegistroPagoCompra (int idrp) throws Exception {
        registropagocompra= registropagocompracontroler.RegistroPagoCompraBuscar(idrp);
        if (registropagocompra != null) {
            
            idRegistroPagoCompra = registropagocompra.getIdRegistroPagoCompra();
            idRegistroCompra = registropagocompra.getIdRegistroComprafk();
            tipoPagoCombo = registropagocompra.getTipoPago();
            String testValuePago1 = tipoPagoCombo;
            for (int i = 0; i < comboBoxTipoPago.getModel().getSize(); i++) {
                if (comboBoxTipoPago.getItemAt(i).equals(testValuePago1)) {
                    System.out.println(i);
                    comboBoxTipoPago.setSelectedIndex(i);
                    break;
                }
            }
            dateChooserFechaAbono.setCalendar(convertirFechaDate(registropagocompra.getFechaAbono()));
            monedaCombo = registropagocompra.getMoneda();
            String testValuePago2 = monedaCombo;
            for (int i = 0; i < comboBoxMonedaPago.getModel().getSize(); i++) {
                if (comboBoxMonedaPago.getItemAt(i).equals(testValuePago2)) {
                    System.out.println(i);
                    comboBoxMonedaPago.setSelectedIndex(i);
                    break;
                }
            }
            txtMontoAbonado.setText(registropagocompra.getMontoAbonado());
            txtNumeroOperacion.setText(registropagocompra.getNumeroOperacion());
            txtObservacion.setText(registropagocompra.getObservacion());
            
            } else {
            JOptionPane.showMessageDialog(null, "Pago de Compra no registrado");
           
            System.out.println("Pago de Compra no registrado");
        }
    }
    
    //---------------- Total Soles y Dolares de los Pagos ------------------------------
     
      void totalSoles(int idrv, String f) throws Exception {
        registropagocompra = registropagocompracontroler.RegistroPagoTotalSoles(idrv, f);

        if (registropagocompra != null) {
            labelMontoSoles.setText(registropagocompra.getMontoTotal());
            labelAbonadoSoles.setText(registropagocompra.getMontoAbonado());
            labelRestoSoles.setText(registropagocompra.getResto());
        } else {

//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }

    }
      
       void totalDolares(int idrvd, String fd) throws Exception {
        registropagocompra = registropagocompracontroler.RegistroPagoTotalDolares(idrvd, fd);

        if (registropagocompra != null) {
            labelMontoDolares.setText(registropagocompra.getMontoTotal());
            labelAbonadoDolares.setText(registropagocompra.getMontoAbonado());
            labelRestoDolares.setText(registropagocompra.getResto());
        } else {
//            JOptionPane.showMessageDialog(null, "tipo cambio no registradas");
            System.out.println("Error");
        }

    }
    
// ------------------------------------ TABLA ---------------------------------------
    void listaRegistroPagoCompra(int idreco) {
        List<RegistroPagoCompra> lista;
        try {
            lista = registropagocompracontroler.RegistroPagoCompraListar(idreco);
            verListaPagos(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

    private void verListaPagos(List<RegistroPagoCompra> lista) {
        
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        tabla.setRowCount(0);
        for (RegistroPagoCompra repago : lista) {
           

            Object[] fila = {repago.getIdRegistroPagoCompra(), repago.getTipoPago(), repago.getFechaAbono(),
                             repago.getMoneda(), repago.getMontoAbonado(), repago.getNumeroOperacion(),
                             repago.getObservacion()};
            tabla.addRow(fila);
        }
    }

//---------------------  Manejo de  Fechas ---------------------------------
   public String fechaActual() {
        Date fecha = new Date();

        SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatofecha.format(fecha);
    }
    
    Calendar convertirFechaDate(String ah) throws ParseException{
   
       Calendar fecha = Calendar.getInstance();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaDate = null;

        fechaDate=formato.parse(ah);

        fecha.setTime(fechaDate);
        
        return fecha;
    }
    
    
    String convertirFechaString(Date fech) {

        Format formatter = new SimpleDateFormat("yyyy-MM-dd ");

        return formatter.format(fech);

    }
    
// ------------------------- Limpiar --------------------------

    void limpiar() throws ParseException {
        
        comboBoxTipoPago.setSelectedIndex(0);
        dateChooserFechaAbono.setCalendar(convertirFechaDate(fechaActual()));
        comboBoxMonedaPago.setSelectedIndex(0);
        txtMontoAbonado.setText("");
        txtNumeroOperacion.setText("");
        txtObservacion.setText("");
        idRegistroPagoCompra = 0;
    }
    
    //-------------------------- Habilitar ----------------------------------
    
    void habilitarInicio(){
        
        comboBoxTipoPago.setEnabled(false);
        dateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaPago.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
        
    }
    void habilitarNuevo(){
    
        comboBoxTipoPago.setEnabled(true);
        dateChooserFechaAbono.setEnabled(true);
        comboBoxMonedaPago.setEnabled(true);
        txtMontoAbonado.setEnabled(true);
        txtNumeroOperacion.setEnabled(true);
        txtObservacion.setEnabled(true);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(true);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }
    void habilitarRegistrar(){
    
        comboBoxTipoPago.setEnabled(false);
        dateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaPago.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }
    void habilitarBuscar(){
    comboBoxTipoPago.setEnabled(false);
        dateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaPago.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(true);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(true);
    }
    void habilitarModificar(){
    
        comboBoxTipoPago.setEnabled(true);
        dateChooserFechaAbono.setEnabled(true);
        comboBoxMonedaPago.setEnabled(true);
        txtMontoAbonado.setEnabled(true);
        txtNumeroOperacion.setEnabled(true);
        txtObservacion.setEnabled(true);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(true);
        buttonEliminar.setEnabled(false);
    }
    void habilitarGuardar(){
    
        comboBoxTipoPago.setEnabled(false);
        dateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaPago.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(true);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(true);
    }
    void habilitarEliminar(){
    
        comboBoxTipoPago.setEnabled(false);
        dateChooserFechaAbono.setEnabled(false);
        comboBoxMonedaPago.setEnabled(false);
        txtMontoAbonado.setEnabled(false);
        txtNumeroOperacion.setEnabled(false);
        txtObservacion.setEnabled(false);

        buttonNuevo.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }
}
