/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.CajaChicaController;
import entity.CajaChica;
import exportarexcel.clsExportarExcel;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vistas.DetalleProformas.obj;

/**
 *
 * @author ARCRODINPC-06
 */
public class CajaChicaRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CajaChicaRegistro
     */
    int idCaja;
    int tabla;
    
    public CajaChicaRegistro() throws Exception {
        initComponents();
        txtFechaCaja.setText(fechaActual());
        listaCajaChica();
        txtEgreso.setText("0");
        txtIngreso.setText("0");
        consultarSumaTotal();
        habilitarInicio();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaCaja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripCaja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEgreso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        buttonCerrar = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelTotalEgresos = new javax.swing.JLabel();
        labelTotalIngresos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        buttonLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonReporteCajaChica = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro Caja Chica");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCaja", "Fecha", "Descripción", "Egreso", "Ingreso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(450);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jLabel1.setText("CAJA CHICA");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Descripción:");

        txtDescripCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripCajaKeyTyped(evt);
            }
        });

        jLabel4.setText("Egreso:");

        jLabel5.setText("Ingreso:");

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Total:");

        labelTotalEgresos.setText("00000000.00");

        labelTotalIngresos.setText("00000000.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Saldo:");

        labelSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSaldo.setText("00000000.00");

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        jButton1.setText("ExportarExcel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonReporteCajaChica.setText("Reporte Caja Chica");
        buttonReporteCajaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReporteCajaChicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotalEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(labelTotalIngresos))
                    .addComponent(labelSaldo))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonNuevo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonRegistrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonGuardar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonEliminar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDescripCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonLimpiar)
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(buttonReporteCajaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addGap(12, 12, 12)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpiar)
                    .addComponent(jButton1)
                    .addComponent(buttonReporteCajaChica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuevo)
                    .addComponent(buttonRegistrar)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelTotalEgresos)
                    .addComponent(labelTotalIngresos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
      dispose();
    }//GEN-LAST:event_buttonCerrarActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        procesar(1);
        listaCajaChica();
        limpiar();
        try {
            consultarSumaTotal();
        } catch (Exception ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarRegistrar();
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        procesar(2);
        listaCajaChica();
        limpiar();
        try {
            consultarSumaTotal();
        } catch (Exception ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarGuardar();
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed

        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el registro, ¿desea continuar?",
                "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            procesar(3);

            listaCajaChica();
            limpiar();
            try {
                consultarSumaTotal();
            } catch (Exception ex) {
                Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
            habilitarEliminar();
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tabla = jTable1.getSelectedRow();
        idCaja = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());
        
        try {
            consultar(idCaja);
        } catch (Exception ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitarBuscar();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
       limpiar();
       habilitarNuevo();
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            limpiar();
            tabla = jTable1.getSelectedRow();
            idCaja = Integer.parseInt(jTable1.getValueAt(tabla, 0).toString());

            try {
                consultar(idCaja);
            } catch (Exception ex) {
                Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        habilitarBuscar();
    }//GEN-LAST:event_jTable1KeyReleased

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
         limpiar();
         habilitarInicio();
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           clsExportarExcel obj = new clsExportarExcel();
        try {
            obj.exportarExcel(jTable1);
        } catch (IOException ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        habilitarModificar();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonReporteCajaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReporteCajaChicaActionPerformed
         ExportarCajaChica expCaja = null;
        try {
            expCaja = new ExportarCajaChica();
        } catch (SQLException ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CajaChicaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal.jDesktopPane1.add(expCaja);
        expCaja.toFront();
        expCaja.setVisible(true);
    }//GEN-LAST:event_buttonReporteCajaChicaActionPerformed

    private void txtDescripCajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripCajaKeyTyped
        String Caracteres = txtDescripCaja.getText();
        if (Caracteres.length() >= 174) {
            JOptionPane.showMessageDialog(null, "Ya no puede ingresar más letras.");
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripCajaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton buttonReporteCajaChica;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTotalEgresos;
    private javax.swing.JLabel labelTotalIngresos;
    private javax.swing.JTextField txtDescripCaja;
    private javax.swing.JTextField txtEgreso;
    private javax.swing.JTextField txtFechaCaja;
    private javax.swing.JTextField txtIngreso;
    // End of variables declaration//GEN-END:variables

CajaChicaController cajaController=new CajaChicaController();
CajaChica caja;

//-------------------------- Consultar -----------------------------------------
    private void consultar(int id) throws Exception {
        caja = cajaController.CajaChicaBuscar(id);
        if (caja != null) {

            idCaja = caja.getIdCajaChica();
            txtFechaCaja.setText(caja.getFechaCaja());
            txtDescripCaja.setText(caja.getDescripCaja());
            txtEgreso.setText(caja.getEgreso());
            txtIngreso.setText(caja.getIngreso());
           

        } else {
            JOptionPane.showMessageDialog(null, "Item no registrado");
            //System.out.println("Error");
        }
    }


// -------------------------- Procesar ------------------------------------------------------
    private void procesar(int op) {
        caja = leerDatos();
        try {
            System.out.println("11111111111");
            String msg = cajaController.CajaChicaProcesar(caja, op);
            JOptionPane.showMessageDialog(null, msg);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Error" + e.getMessage());
        }
    }

//------------------------------ Leer Datos-------------------------------------
    private CajaChica leerDatos() {
        CajaChica caj = new CajaChica();

        caj.setIdCajaChica(idCaja);
        caj.setFechaCaja(txtFechaCaja.getText());
        caj.setDescripCaja(txtDescripCaja.getText());
        caj.setEgreso(txtEgreso.getText());
        caj.setIngreso(txtIngreso.getText());

        return caj;
    }

 //-------------------------------- Tabla --------------------------------------
    void listaCajaChica() {
        List<CajaChica> lista;
        try {
            lista = cajaController.CajaChicaListar();
            verCajaChica(lista);

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("ERROR: " + e.getMessage());
        }
    }

     private void verCajaChica(List<CajaChica> lista) {

        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        tabla.setRowCount(0);
        for (CajaChica cajChic : lista) {
            Object[] fila = {cajChic.getIdCajaChica(),cajChic.getFechaCaja(), cajChic.getDescripCaja(), cajChic.getEgreso(), cajChic.getIngreso()};
            tabla.addRow(fila);

        }
    }

    // ------------------------ Fecha --> Indica la fecha del dia --------------------
    public String fechaActual() {
        Date fecha = new Date();

        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY-MM-dd");
        return formatofecha.format(fecha);
    }

//---------------- Limpiar --------------------------------------
    void limpiar(){
     txtFechaCaja.setText(fechaActual());
     txtDescripCaja.setText("");
     txtEgreso.setText("0");
     txtIngreso.setText("0");
    }
    
   // -----------------Suma------------------------------
    void consultarSumaTotal() throws Exception {
        caja = cajaController.CajaChicaCalcular();

        if (caja != null) {
            if (caja.getTotalEgreso() != null) {
                labelTotalEgresos.setText(caja.getTotalEgreso());
            } else {
                labelTotalEgresos.setText("00000000.00");
            }
            if (caja.getTotalIngreso() != null) {
                 labelTotalIngresos.setText(caja.getTotalIngreso());
            } else {
                 labelTotalIngresos.setText("00000000.00");
            }
            if (caja.getDiferencia() != null) {
                labelSaldo.setText(caja.getDiferencia());
            } else {
                labelSaldo.setText("00000000.00");
            }
//            labelTotalEgresos.setText(caja.getTotalEgreso());
//            labelTotalIngresos.setText(caja.getTotalIngreso());
//            labelSaldo.setText(caja.getDiferencia());
//           

        } else {
            JOptionPane.showMessageDialog(null, "Operacion Invalida");
            //System.out.println("Error");
        }
    }
    
    //------------------------- Habilitar -----------------------------------
    
     public void habilitarInicio() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);
        buttonModificar.setEnabled(false);

        txtFechaCaja.setEnabled(false);
        txtDescripCaja.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtIngreso.setEnabled(false);

    }

    public void habilitarNuevo() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(true);
        buttonNuevo.setEnabled(false);
        buttonModificar.setEnabled(false);

        txtFechaCaja.setEnabled(true);
        txtDescripCaja.setEnabled(true);
        txtEgreso.setEnabled(true);
        txtIngreso.setEnabled(true);

    }

    public void habilitarGuardar() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);
        buttonModificar.setEnabled(false);

        txtFechaCaja.setEnabled(false);
        txtDescripCaja.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtIngreso.setEnabled(false); 

    }

    public void habilitarRegistrar() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);

        txtFechaCaja.setEnabled(false);
        txtDescripCaja.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtIngreso.setEnabled(false);
    }

    public void habilitarBuscar() {
        buttonEliminar.setEnabled(true);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);
        buttonModificar.setEnabled(true);

        txtFechaCaja.setEnabled(false);
        txtDescripCaja.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtIngreso.setEnabled(false);

    }

    public void habilitarEliminar() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(false);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);
        buttonModificar.setEnabled(false);

        txtFechaCaja.setEnabled(false);
        txtDescripCaja.setEnabled(false);
        txtEgreso.setEnabled(false);
        txtIngreso.setEnabled(false);

    }
    
    
    public void habilitarModificar() {
        buttonEliminar.setEnabled(false);
        buttonGuardar.setEnabled(true);
        buttonRegistrar.setEnabled(false);
        buttonNuevo.setEnabled(true);
        buttonModificar.setEnabled(false);

        txtFechaCaja.setEnabled(true);
        txtDescripCaja.setEnabled(true);
        txtEgreso.setEnabled(true);
        txtIngreso.setEnabled(true);

    }
    
   

}
