/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ARCRODINPC-05
 */
public class AAAAEjemploDeFecha extends javax.swing.JInternalFrame {

    /**
     * Creates new form AAAAEjemploDeFecha
     */
    int dia, diaj, mes, anio;
    static String f, fn,ff;
    String Valor_dia;
    int i, j, n = 0, t = 0;
    
    public AAAAEjemploDeFecha() {
        initComponents();
        diaFecha();
        jTextField1.setText(f);
        try {
            diaSemana(jTextField1.getText());
        } catch (ParseException ex) {
            Logger.getLogger(AAAAEjemploDeFecha.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(Valor_dia);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);

        jButton1.setText("Sumar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        j=Integer.parseInt(jTextField4.getText());
        try { 
            diasSabadoDomingo(j);
        } catch (ParseException ex) {
            Logger.getLogger(AAAAEjemploDeFecha.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField3.setText(ff);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    void diaFecha(){
    
    Calendar fecha = Calendar.getInstance();
         anio = fecha.get(Calendar.YEAR);
         mes = fecha.get(Calendar.MONTH) + 1;
         dia = fecha.get(Calendar.DAY_OF_MONTH);
        
         f= dia+"/"+mes+"/"+anio;
   }
    
   
    void CompararDiasFinMes(int d, int m, int a) throws ParseException {

        if ((m == 1 || m == 3 || m == 5 || m == 7 || m == 8 || m == 10) && d > 31) {
            d = d - 31;
            dia = d;
            m = m + 1;
            mes = m;
            anio = a;
            fn = dia + "/" + mes + "/" + anio;
        } else if ((m == 4 || m == 6 || m == 9 || m == 11) && d > 30) {
            d = d - 30;
            dia = d;
            m = m + 1;
            mes = m;
            anio = a;
            fn = dia + "/" + mes + "/" + anio;
        } else if (m == 2) {
            if (d > 28 && a % 4 != 0) {
                d = d - 28;
                dia = d;
                m = m + 1;
                mes = m;
                anio = a;
                fn = dia + "/" + mes + "/" + anio;

            } else if (d > 29 && a % 4 == 0) {
                d = d - 29;
                dia = d;
                m = m + 1;
                mes = m;
                anio = a;
                fn = dia + "/" + mes + "/" + anio;
            }
            fn = dia + "/" + mes + "/" + anio;
        } else if (m == 12 && d > 31) {
            d = d - 31;
            dia = d;
            m = m + 1;
            mes = m;
            a = a + 1;
            anio = a;
            fn = dia + "/" + mes + "/" + anio;
        } else {
            fn = dia + "/" + mes + "/" + anio;
        }

        diaSemana(fn);
        System.out.println("luego de suma total" + Valor_dia);
    }

    void diaSemana(String ah) throws ParseException {
        Calendar fecha = Calendar.getInstance();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;

        fechaDate = formato.parse(ah);

        fecha.setTime(fechaDate);

        int diaSemana = fecha.get(Calendar.DAY_OF_WEEK);
        if (diaSemana == 1) {
            Valor_dia = "Domingo";
        } else if (diaSemana == 2) {
            Valor_dia = "Lunes";
        } else if (diaSemana == 3) {
            Valor_dia = "Martes";
        } else if (diaSemana == 4) {
            Valor_dia = "Miercoles";
        } else if (diaSemana == 5) {
            Valor_dia = "Jueves";
        } else if (diaSemana == 6) {
            Valor_dia = "Viernes";
        } else if (diaSemana == 7) {
            Valor_dia = "Sabado";
        }
    }

    void diasSabadoDomingo(int v) throws ParseException {

        System.out.println("****************************************************************************");
        System.out.println("dia de inicio:" + dia + "mes: " + mes + "anio" + anio);

        for (i = 1; i <= v; i++) {
            System.out.println("empezando el for i:" + i + " dia:" + dia);

            dia = dia + 1;
            fn = dia + "/" + mes + "/" + anio;
            CompararDiasFinMes(dia, mes, anio);
            fn = dia + "/" + mes + "/" + anio;
            System.out.println("fecha"+fn);
            diaSemana(fn);
            System.out.println("Dia te" + Valor_dia);
            
            if ("Viernes".equals(Valor_dia) && i!=v) {
                dia = dia + 2;
                System.out.println("terminando el if:" + i + " dia:" + dia);
                fn = dia + "/" + mes + "/" + anio;
            }
            
            fn = dia + "/" + mes + "/" + anio;
            System.out.println("iteracion: " + i);
            System.out.println("terminando el for i:" + i + " dia:" + dia);
        }

        diaSemana(fn);
        ff = fn;
        System.out.println("Dia terminando el for" + Valor_dia);
        identificarfechaLunes(Valor_dia,dia);
    }
    
    
    void identificarfechaLunes(String valordia, int g){
        
          if ("Domingo".equals(valordia)) {
            g=g-6;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Lunes".equals(valordia)) {
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Martes".equals(valordia)) {
            g=g-1;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Miercoles".equals(valordia)) {
            g=g-2;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Jueves".equals(valordia)) {
            g=g-3;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Viernes".equals(valordia)) {
            g=g-4;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        } else if ("Sabado".equals(valordia)) {
            g=g-5;
            jLabel1.setText(g + "/" + mes + "/" + anio);
        }
    
    
    }
}
